source "https://rubygems.org"

gem "jekyll", "4.4.1"
gem "github-pages-health-check", "1.18.5"
gem "jekyll-avatar", "0.8.0"
gem "jekyll-coffeescript", "1.1.1"
gem "jekyll-default-layout", "0.1.5"
gem "jekyll-feed", "0.17.0"
gem "jekyll-gist", "1.5.0"
gem "jekyll-git-hash"
gem "jekyll-include-cache", "0.2.1"
gem "jekyll-optional-front-matter", "0.3.2"
gem "jekyll-paginate", "1.1.0"
gem "jekyll-readme-index", "0.3.0"
gem "jekyll-redirect-from", "0.16.0"
gem "jekyll-regex-replace", "1.1.0"
gem "jekyll-relative-links", "0.7.0"
gem "jekyll-sass-converter", "3.1.0"
gem "jekyll-seo-tag", "2.8.0"
gem "jekyll-sitemap", "1.4.0"
gem "jekyll-swiss", "1.0.0"
gem "jekyll-theme-architect", "0.2.0"
gem "jekyll-theme-cayman", "0.2.0"
gem "jekyll-theme-dinky", "0.2.0"
gem "jekyll-theme-hacker", "0.2.0"
gem "jekyll-theme-leap-day", "0.2.0"
gem "jekyll-theme-merlot", "0.2.0"
gem "jekyll-theme-midnight", "0.2.0"
gem "jekyll-theme-minimal", "0.2.0"
gem "jekyll-theme-modernist", "0.2.0"
gem "jekyll-theme-primer", "0.6.0"
gem "jekyll-theme-slate", "0.2.0"
gem "jekyll-theme-tactile", "0.2.0"
gem "jekyll-theme-time-machine", "0.2.0"
gem "jekyll-titles-from-headings", "0.5.3"
gem "kramdown-parser-gfm", "1.1.0"
gem "kramdown", "2.5.1"
gem "liquid", "4.0.4"
gem "minima", git: "https://github.com/duckdb/minima.git", branch: "master"
gem "rouge", git: "https://github.com/duckdb/rouge.git", branch: "duckdb"

gem "safe_yaml", "1.0.5"
gem "sass", "3.7.4"

gem "webrick", "~> 1.9"
gem 'word_wrap', '~> 1.0'

gem "jekyll-toc", "~> 0.19.0"
