import duckdb

import inspect

import warnings

FORMATTER_TEXT = """---
layout: docu
redirect_from:
- /docs/api/python/relational_api
- /docs/api/python/relational_api/
- /docs/clients/python/relational_api
title: Relational API
---

<!-- Generated by scripts/generate_python_relational_docs.py -->

"""

DEFINITION_MEMBER_LIST = [
    "columns",
    "describe",
    "description",
    "dtypes",
    "explain",
    "query",
    "set_alias",
    "alias",
    "shape",
    "show",
    "sql_query",
    "type",
    "types",
]
TRANSFORMATION_MEMBER_LIST = [
    "aggregate",
    "apply",
    "cross",
    "except_",
    "filter",
    "insert",
    "insert_into",
    "intersect",
    "join",
    "limit",
    "map",
    "order",
    "project",
    "select",
    "sort",
    "union",
    "update",
]
FUNCTION_MEMBER_LIST = [
    "any_value",
    "arg_max",
    "arg_min",
    "avg",
    "bit_and",
    "bit_or",
    "bit_xor",
    "bitstring_agg",
    "bool_and",
    "bool_or",
    "count",
    "cume_dist",
    "dense_rank",
    "distinct",
    "favg",
    "first",
    "first_value",
    "fsum",
    "geomean",
    "histogram",
    "lag",
    "last",
    "last_value",
    "lead",
    "list",
    "max",
    "mean",
    "median",
    "min",
    "mode",
    "n_tile",
    "nth_value",
    "percent_rank",
    "product",
    "quantile",
    "quantile_cont",
    "quantile_disc",
    "rank",
    "rank_dense",
    "row_number",
    "select_dtypes",
    "select_types",
    "std",
    "stddev",
    "stddev_pop",
    "stddev_samp",
    "string_agg",
    "sum",
    "unique",
    "value_counts",
    "var",
    "var_pop",
    "var_samp",
    "variance",
]
OUTPUT_MEMBER_LIST = [
    "arrow",
    "close",
    "create",
    "create_view",
    "df",
    "execute",
    "fetch_arrow_reader",
    "fetch_arrow_table",
    "fetch_df_chunk",
    "fetchall",
    "fetchdf",
    "fetchmany",
    "fetchnumpy",
    "fetchone",
    "pl",
    "record_batch",
    "tf",
    "to_arrow_table",
    "to_csv",
    "to_df",
    "to_parquet",
    "to_table",
    "to_view",
    "torch",
    "write_csv",
    "write_parquet",
]

CREATION_MEMBER_LIST = [
    'from_arrow',
    'from_csv_auto',
    'from_df',
    'from_parquet',
    'from_query',
    'query',
    'read_csv',
    'read_json',
    'read_parquet',
    'sql',
    'table',
    'table_function',
    'values',
    'view',
]

SECTION_MAP = {
    "Relation Creation": {
        "id": 1,
        "description": "This section contains the details on how a relation is created.",
    },
    "Relation Definition Details": {
        "id": 2,
        "description": "This section contains the details on how to inspect a relation.",
    },
    "Transformation": {
        "id": 3,
        "description": "This section contains the methods which can be used to chain queries.\
        The transformation methods are lazy evaluated, therefore not executed.\
        The execution happens at [output](#output) or [function](#functions) call.",
    },
    "Functions": {
        "id": 4,
        "description": "This section contains the functions which can be applied to an relation, \
        in order to get a (scalar) result. When a function is called the SQL is executed.",
    },
    "Output": {
        "id": 5,
        "description": "This section contains the functions which will trigger an SQL execution and retrieve the data.",
    },
}


DEFAULT_EXAMPLE = '''```python
import duckdb

duckdb_conn = duckdb.connect()

duckdb_conn.sql("drop table if exists code_example")

duckdb_conn.sql("""
        select 
            gen_random_uuid() as id, 
            concat('value is ', case when mod(range,2)=0 then 'even' else 'uneven' end) as description,
            range as value, 
            now() + concat(range,' ', 'minutes')::interval as created_timestamp
        from range(1, 10)
    """
).to_table("code_example")

rel = duckdb_conn.table("code_example")

{code_example}
```
'''

DEFAULT_RESULT = "```text\n{result}\n```"

DEFINITION_MEMBER_CODE_EXAMPLE_MAP = {
    'columns': {
        'example': 'rel.columns',
        'result': " ['id', 'description', 'value', 'created_timestamp']",
    },
    'describe': {
        'example': 'rel.describe()',
        'result': """
┌─────────┬──────────────────────────────────────┬─────────────────┬────────────────────┬────────────────────────────┐
│  aggr   │                  id                  │   description   │       value        │     created_timestamp      │
│ varchar │               varchar                │     varchar     │       double       │          varchar           │
├─────────┼──────────────────────────────────────┼─────────────────┼────────────────────┼────────────────────────────┤
│ count   │ 9                                    │ 9               │                9.0 │ 9                          │
│ mean    │ NULL                                 │ NULL            │                5.0 │ NULL                       │
│ stddev  │ NULL                                 │ NULL            │ 2.7386127875258306 │ NULL                       │
│ min     │ 08fdcbf8-4e53-4290-9e81-423af263b518 │ value is even   │                1.0 │ 2025-04-09 15:41:20.642+02 │
│ max     │ fb10390e-fad5-4694-91cb-e82728cb6f9f │ value is uneven │                9.0 │ 2025-04-09 15:49:20.642+02 │
│ median  │ NULL                                 │ NULL            │                5.0 │ NULL                       │
└─────────┴──────────────────────────────────────┴─────────────────┴────────────────────┴────────────────────────────┘ 
""",
    },
    'description': {
        'example': 'rel.description',
        'result': """
[('id', 'UUID', None, None, None, None, None),
 ('description', 'STRING', None, None, None, None, None),
 ('value', 'NUMBER', None, None, None, None, None),
 ('created_timestamp', 'DATETIME', None, None, None, None, None)]  
""",
    },
    'dtypes': {
        'example': 'rel.dtypes',
        'result': ' [UUID, VARCHAR, BIGINT, TIMESTAMP WITH TIME ZONE]',
    },
    'explain': {
        'example': 'rel.explain()',
        'result': """
┌───────────────────────────┐\n│         SEQ_SCAN          │\n│    ────────────────────   │\n│    Table: code_example    │\n│   Type: Sequential Scan   │\n│                           │\n│        Projections:       │\n│             id            │\n│        description        │\n│           value           │\n│     created_timestamp     │\n│                           │\n│          ~9 Rows          │\n└───────────────────────────┘\n\n
""",
    },
    'set_alias': {
        'example': "rel.set_alias('abc').select('abc.id')",
        'result': 'In the SQL query, the alias will be `abc`',
    },
    'alias': {'example': 'rel.alias', 'result': 'unnamed_relation_43c808c247431be5'},
    'shape': {'example': 'rel.shape', 'result': '(9, 4)'},
    'show': {
        'example': 'rel.show()',
        'result': """
┌──────────────────────────────────────┬─────────────────┬───────┬────────────────────────────┐
│                  id                  │   description   │ value │     created_timestamp      │
│                 uuid                 │     varchar     │ int64 │  timestamp with time zone  │
├──────────────────────────────────────┼─────────────────┼───────┼────────────────────────────┤
│ 642ea3d7-793d-4867-a759-91c1226c25a0 │ value is uneven │     1 │ 2025-04-09 15:41:20.642+02 │
│ 6817dd31-297c-40a8-8e40-8521f00b2d08 │ value is even   │     2 │ 2025-04-09 15:42:20.642+02 │
│ 45143f9a-e16e-4e59-91b2-3a0800eed6d6 │ value is uneven │     3 │ 2025-04-09 15:43:20.642+02 │
│ fb10390e-fad5-4694-91cb-e82728cb6f9f │ value is even   │     4 │ 2025-04-09 15:44:20.642+02 │
│ 111ced5c-9155-418e-b087-c331b814db90 │ value is uneven │     5 │ 2025-04-09 15:45:20.642+02 │
│ 66a870a6-aef0-4085-87d5-5d1b35d21c66 │ value is even   │     6 │ 2025-04-09 15:46:20.642+02 │
│ a7e8e796-bca0-44cd-a269-1d71090fb5cc │ value is uneven │     7 │ 2025-04-09 15:47:20.642+02 │
│ 74908d48-7f2d-4bdd-9c92-1e7920b115b5 │ value is even   │     8 │ 2025-04-09 15:48:20.642+02 │
│ 08fdcbf8-4e53-4290-9e81-423af263b518 │ value is uneven │     9 │ 2025-04-09 15:49:20.642+02 │
└──────────────────────────────────────┴─────────────────┴───────┴────────────────────────────┘
""",
    },
    'sql_query': {
        'example': 'rel.sql_query()',
        'result': 'SELECT * FROM main.code_example',
    },
    'type': {'example': 'rel.type', 'result': 'QUERY_RELATION'},
    'types': {
        'example': 'rel.types',
        'result': '[UUID, VARCHAR, BIGINT, TIMESTAMP WITH TIME ZONE]',
    },
}

FUNCTION_MEMBER_CODE_EXAMPLE_MAP = {
    'any_value': {
        'example': "rel.any_value('id')",
        'result': """
┌──────────────────────────────────────┐
│            any_value(id)             │
│                 uuid                 │
├──────────────────────────────────────┤
│ 642ea3d7-793d-4867-a759-91c1226c25a0 │
└──────────────────────────────────────┘
""",
    },
    'arg_max': {
        'example': 'rel.arg_max(arg_column="value", value_column="value", groups="description", projected_columns="description")',
        'result': """
┌─────────────────┬───────────────────────────┐
│   description   │ arg_max("value", "value") │
│     varchar     │           int64           │
├─────────────────┼───────────────────────────┤
│ value is uneven │                         9 │
│ value is even   │                         8 │
└─────────────────┴───────────────────────────┘
""",
    },
    'arg_min': {
        'example': 'rel.arg_min(arg_column="value", value_column="value", groups="description", projected_columns="description")',
        'result': """
┌─────────────────┬───────────────────────────┐
│   description   │ arg_min("value", "value") │
│     varchar     │           int64           │
├─────────────────┼───────────────────────────┤
│ value is even   │                         2 │
│ value is uneven │                         1 │
└─────────────────┴───────────────────────────┘
""",
    },
    'avg': {
        'example': "rel.avg('value')",
        'result': """
┌──────────────┐
│ avg("value") │
│    double    │
├──────────────┤
│          5.0 │
└──────────────┘
 """,
    },
    'bit_and': {
        'example': """
rel = rel.select("description, value::bit as value_bit")

rel.bit_and(column="value_bit", groups="description", projected_columns="description")
""",
        'result': """
┌─────────────────┬──────────────────────────────────────────────────────────────────┐
│   description   │                        bit_and(value_bit)                        │
│     varchar     │                               bit                                │
├─────────────────┼──────────────────────────────────────────────────────────────────┤
│ value is uneven │ 0000000000000000000000000000000000000000000000000000000000000001 │
│ value is even   │ 0000000000000000000000000000000000000000000000000000000000000000 │
└─────────────────┴──────────────────────────────────────────────────────────────────┘    
""",
    },
    'bit_or': {
        'example': """
rel = rel.select("description, value::bit as value_bit")

rel.bit_or(column="value_bit", groups="description", projected_columns="description")
""",
        'result': """
┌─────────────────┬──────────────────────────────────────────────────────────────────┐
│   description   │                        bit_or(value_bit)                         │
│     varchar     │                               bit                                │
├─────────────────┼──────────────────────────────────────────────────────────────────┤
│ value is uneven │ 0000000000000000000000000000000000000000000000000000000000001111 │
│ value is even   │ 0000000000000000000000000000000000000000000000000000000000001110 │
└─────────────────┴──────────────────────────────────────────────────────────────────┘    
""",
    },
    'bit_xor': {
        'example': """
rel = rel.select("description, value::bit as value_bit")

rel.bit_xor(column="value_bit", groups="description", projected_columns="description")
""",
        'result': """
┌─────────────────┬──────────────────────────────────────────────────────────────────┐
│   description   │                        bit_xor(value_bit)                        │
│     varchar     │                               bit                                │
├─────────────────┼──────────────────────────────────────────────────────────────────┤
│ value is even   │ 0000000000000000000000000000000000000000000000000000000000001000 │
│ value is uneven │ 0000000000000000000000000000000000000000000000000000000000001001 │
└─────────────────┴──────────────────────────────────────────────────────────────────┘
""",
    },
    'bitstring_agg': {
        'example': 'rel.bitstring_agg(column="value", groups="description", projected_columns="description")',
        'result': """
┌─────────────────┬────────────────────────┐
│   description   │ bitstring_agg("value") │
│     varchar     │          bit           │
├─────────────────┼────────────────────────┤
│ value is uneven │ 101010101              │
│ value is even   │ 010101010              │
└─────────────────┴────────────────────────┘
""",
    },
    'bool_and': {
        'example': """
rel = rel.select("description, mod(value,2)::boolean as uneven")

rel.bool_and(column="uneven", groups="description", projected_columns="description")
""",
        'result': """
┌─────────────────┬──────────────────┐
│   description   │ bool_and(uneven) │
│     varchar     │     boolean      │
├─────────────────┼──────────────────┤
│ value is even   │ false            │
│ value is uneven │ true             │
└─────────────────┴──────────────────┘
""",
    },
    'bool_or': {
        'example': """
rel = rel.select("description, mod(value,2)::boolean as uneven")

rel.bool_or(column="uneven", groups="description", projected_columns="description")
""",
        'result': """
┌─────────────────┬─────────────────┐
│   description   │ bool_or(uneven) │
│     varchar     │     boolean     │
├─────────────────┼─────────────────┤
│ value is even   │ false           │
│ value is uneven │ true            │
└─────────────────┴─────────────────┘                
""",
    },
    'count': {'example': 'rel.count()', 'result': ''},
    'cume_dist': {'example': 'rel.cume_dist()', 'result': ''},
    'dense_rank': {'example': 'rel.dense_rank()', 'result': ''},
    'distinct': {'example': 'rel.distinct()', 'result': ''},
    'favg': {'example': 'rel.favg()', 'result': ''},
    'first': {'example': 'rel.first()', 'result': ''},
    'first_value': {'example': 'rel.first_value()', 'result': ''},
    'fsum': {'example': 'rel.fsum()', 'result': ''},
    'geomean': {'example': 'rel.geomean()', 'result': ''},
    'histogram': {'example': 'rel.histogram()', 'result': ''},
    'lag': {'example': 'rel.lag()', 'result': ''},
    'last': {'example': 'rel.last()', 'result': ''},
    'last_value': {'example': 'rel.last_value()', 'result': ''},
    'lead': {'example': 'rel.lead()', 'result': ''},
    'list': {'example': 'rel.list()', 'result': ''},
    'max': {'example': 'rel.max()', 'result': ''},
    'mean': {'example': 'rel.mean()', 'result': ''},
    'median': {'example': 'rel.median()', 'result': ''},
    'min': {'example': 'rel.min()', 'result': ''},
    'mode': {'example': 'rel.mode()', 'result': ''},
    'n_tile': {'example': 'rel.n_tile()', 'result': ''},
    'nth_value': {'example': 'rel.nth_value()', 'result': ''},
    'percent_rank': {'example': 'rel.percent_rank()', 'result': ''},
    'product': {'example': 'rel.product()', 'result': ''},
    'quantile': {'example': 'rel.quantile()', 'result': ''},
    'quantile_cont': {'example': 'rel.quantile_cont()', 'result': ''},
    'quantile_disc': {'example': 'rel.quantile_disc()', 'result': ''},
    'rank': {'example': 'rel.rank()', 'result': ''},
    'rank_dense': {'example': 'rel.rank_dense()', 'result': ''},
    'row_number': {'example': 'rel.row_number()', 'result': ''},
    'select_dtypes': {'example': 'rel.select_dtypes()', 'result': ''},
    'select_types': {'example': 'rel.select_types()', 'result': ''},
    'std': {'example': 'rel.std()', 'result': ''},
    'stddev': {'example': 'rel.stddev()', 'result': ''},
    'stddev_pop': {'example': 'rel.stddev_pop()', 'result': ''},
    'stddev_samp': {'example': 'rel.stddev_samp()', 'result': ''},
    'string_agg': {'example': 'rel.string_agg()', 'result': ''},
    'sum': {'example': 'rel.sum()', 'result': ''},
    'unique': {'example': 'rel.unique()', 'result': ''},
    'value_counts': {'example': 'rel.value_counts()', 'result': ''},
    'var': {'example': 'rel.var()', 'result': ''},
    'var_pop': {'example': 'rel.var_pop()', 'result': ''},
    'var_samp': {'example': 'rel.var_samp()', 'result': ''},
    'variance': {'example': 'rel.variance()', 'result': ''},
}

TRANSFORMATION_MEMBER_CODE_EXAMPLE_MAP = {
    "aggregate": {
        "example": "print(rel.aggregate('max(value)'))",
        "result": """
┌──────────────┐
│ max("value") │
│    int64     │
├──────────────┤
│            9 │
└──────────────┘
        """,
    },
}

CODE_EXAMPLE_MAP = {
    **DEFINITION_MEMBER_CODE_EXAMPLE_MAP,
    **FUNCTION_MEMBER_CODE_EXAMPLE_MAP,
    **TRANSFORMATION_MEMBER_CODE_EXAMPLE_MAP,
}


def get_duckdb_conn():
    duckdb_conn = duckdb.connect()
    duckdb_conn.sql(
        """
        CREATE TABLE relational_api_members(
            class_name text,
            member_name text,
            section text,
            section_id integer,
            member_signature text,
            member_description text,
            member_toc_line text,
            member_example text,
            member_result text,
            primary key (class_name, member_name)
        )
    """
    )
    return duckdb_conn


def populate_member_details(relational_api_table, class_name, member_list, section):

    for class_member in inspect.getmembers(class_name):
        class_member_name = class_member[0]
        class_member_value = class_member[1]
        if class_member_name not in member_list:
            continue
        member_signature = None
        member_description = None
        if inspect.getdoc(class_member_value):
            member_docs = inspect.getdoc(class_member_value).split("\n\n")
            if len(member_docs) >= 2:
                member_signature = member_docs[0]
                member_description = '\n'.join(member_docs[1:])
            else:
                member_description = member_docs[0]

            if class_member_name in ['from_parquet', 'read_parquet']:
                member_description = "Create a relation object from the Parquet files"

        relational_api_table.insert(
            [
                class_name.__name__,
                class_member_name,
                section,
                SECTION_MAP.get(section).get("id"),
                f"```python\n {member_signature}\n```" if member_signature else None,
                member_description,
                f"| [`{class_member_name}`](#{class_member_name}) | {member_description} |",
                (
                    DEFAULT_EXAMPLE.format(
                        code_example=CODE_EXAMPLE_MAP.get(class_member_name).get(
                            "example"
                        )
                    )
                    if CODE_EXAMPLE_MAP.get(class_member_name)
                    and CODE_EXAMPLE_MAP.get(class_member_name).get("default", True)
                    else (
                        CODE_EXAMPLE_MAP.get(class_member_name).get("example")
                        if CODE_EXAMPLE_MAP.get(class_member_name)
                        else None
                    )
                ),
                (
                    DEFAULT_RESULT.format(
                        result=CODE_EXAMPLE_MAP.get(class_member_name).get("result")
                    )
                    if CODE_EXAMPLE_MAP.get(class_member_name)
                    else None
                ),
            ]
        )


def generate_from_db(relational_api_table):
    with open("docs/preview/clients/python/relational_api.md", "w") as f:
        f.write(FORMATTER_TEXT)
        f.write("\n")

        # write TOC
        f.write("## Index")

        toc_section = (
            relational_api_table.select('section', "section_id", 'member_toc_line')
            .string_agg(
                'member_toc_line',
                sep='\n',
                groups='section, section_id',
                projected_columns='section, section_id',
            )
            .order("section_id")
        )

        for section in toc_section.fetchall():
            f.write(
                f"\n\n**[{section[0]}](#{section[0].lower().replace(" ", "-")})**\n\n"
            )
            f.write("| Name | Description |\n|:--|:-------|\n")
            f.write(section[2])

        f.write("\n\n")

        # write section details
        section_details = (
            relational_api_table.select(
                """
            section,
            section_id,
            concat('### ',member_name) as header_member_name, 
            case when member_signature is not null then '\n\n#### Signature\n\n' else NULL end as header_signature, 
            member_signature,
            case when member_description is not null then '\n\n#### Description\n\n' else NULL end as header_description, 
            member_description,
            case when member_example is not null then '\n\n##### Example\n\n' else NULL end as header_example,
            member_example,
            case when member_result is not null then '\n\n##### Result\n\n' else NULL end as header_result,
            member_result
        """
            )
            .select(
                """
                section, 
                section_id, 
                concat(
                    header_member_name, 
                    header_description, 
                    member_description, 
                    header_signature, 
                    member_signature, 
                    header_example, 
                    member_example, 
                    header_result, 
                    member_result
                ) as detailed_section
            """
            )
            .string_agg(
                "detailed_section",
                sep='\n\n----\n\n',
                groups='section, section_id',
                projected_columns='section, section_id',
            )
            .order("section_id")
        )

        for section in section_details.fetchall():
            f.write(f"\n\n## {section[0]} \n\n")
            f.write(SECTION_MAP.get(section[0]).get("description"))
            f.write("\n\n")
            f.write(section[2])

        f.write("\n")


def check_fully_documented(class_name, configured_in_script, class_members):
    if too_many_doc_members := list(set(configured_in_script) - set(class_members)):
        warnings.warn(
            f"The following members are not in the {class_name} anymore!: {too_many_doc_members}"
        )
    if undocumented_members := list(set(class_members) - set(configured_in_script)):
        warnings.warn(
            f"There are members which are not documented for {class_name}: {undocumented_members}"
        )


def main():
    check_fully_documented(
        class_name="DuckDBPyRelation",
        configured_in_script=(
            DEFINITION_MEMBER_LIST
            + TRANSFORMATION_MEMBER_LIST
            + FUNCTION_MEMBER_LIST
            + OUTPUT_MEMBER_LIST
        ),
        class_members=[
            member[0]
            for member in inspect.getmembers(duckdb.DuckDBPyRelation)
            if not member[0].startswith("_")
        ],
    )

    check_fully_documented(
        class_name="DuckDBPyConnection",
        configured_in_script=CREATION_MEMBER_LIST,
        class_members=[
            member[0]
            for member in inspect.getmembers(duckdb.DuckDBPyConnection)
            if inspect.getdoc(member[1])
            and '-> duckdb.duckdb.DuckDBPyRelation' in inspect.getdoc(member[1])
        ],
    )

    duckdb_conn = get_duckdb_conn()

    relational_api_table = duckdb_conn.table("relational_api_members")

    populate_member_details(
        relational_api_table=relational_api_table,
        class_name=duckdb.DuckDBPyConnection,
        member_list=CREATION_MEMBER_LIST,
        section="Relation Creation",
    )

    populate_member_details(
        relational_api_table=relational_api_table,
        class_name=duckdb.DuckDBPyRelation,
        member_list=DEFINITION_MEMBER_LIST,
        section="Relation Definition Details",
    )

    populate_member_details(
        relational_api_table=relational_api_table,
        class_name=duckdb.DuckDBPyRelation,
        member_list=TRANSFORMATION_MEMBER_LIST,
        section="Transformation",
    )
    populate_member_details(
        relational_api_table=relational_api_table,
        class_name=duckdb.DuckDBPyRelation,
        member_list=FUNCTION_MEMBER_LIST,
        section="Functions",
    )

    populate_member_details(
        relational_api_table=relational_api_table,
        class_name=duckdb.DuckDBPyRelation,
        member_list=OUTPUT_MEMBER_LIST,
        section="Output",
    )

    generate_from_db(relational_api_table)


if __name__ == "__main__":
    main()
